image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo npm install sfdx-cli --global 
      echo npm install @salesforce/cli --global
      
    command: sfdx --version

vscode:
  extensions:
    - salesforce.salesforce-vscode-slds
    - salesforce.salesforcedx-vscode
    - salesforce.salesforcedx-vscode-apex
    - salesforce.salesforcedx-vscode-apex-debugger
    - salesforce.salesforcedx-vscode-apex-replay-debugger
    - salesforce.salesforcedx-vscode-core
    - salesforce.salesforcedx-vscode-expanded
    - salesforce.salesforcedx-vscode-lightning
    - salesforce.salesforcedx-vscode-lwc
    - salesforce.salesforcedx-vscode-soql
    - salesforce.salesforcedx-vscode-visualforce
    - redhat.vscode-xml@0.11.0:UisfuLs/74cHN6OonFG4YA==
    